# syncRevision: 30565a3ae746543a
metadata:
  name: deploy-test-1772764108
  labels: {}
  annotations: {}
  finalizers: []
  creationTimestamp: '2026-03-06T02:28:28.440200Z'
spec:
  hostname: deploy-test-1772764108.homelab.local
  os:
    distro: ubuntu-24.04-live
    arch: x86_64
  macAddress: 02:00:00:00:00:98
  hardware:
    cpu: 2
    ramGiB: 4
  storage:
    disk_name: sda
    partitions:
    - partition_type: primary
      alloc_type: percentage
      size: 100
      fs_type: ext4
      flags:
      - lvm
  networking:
    interfaces:
    - name: eth0
      dhcp: true
    vlans: []
  users:
  - name: admin
    groups:
    - wheel
  groups:
  - test_nodes
  featureFlags:
    provisioned:
      enabled: false
    k8s:
      enabled: false
      role: worker
    monitoring:
      enabled: true
    backup:
      enabled: false
    daemon:
      enabled: true
  pauseReconciliation: false
  tags:
    env: deploy-test
status:
  conditions:
  - type: Reachable
    status: 'False'
    lastTransitionTime: '2026-03-06T02:28:28.447584Z'
  - type: DaemonReady
    status: 'False'
    lastTransitionTime: '2026-03-06T02:28:28.447717Z'
  features:
    provisioned:
      installed: false
    k8s:
      installed: false
    monitoring:
      installed: false
    backup:
      installed: false
    daemon:
      installed: false
  inventorySynced: false
  hostvarsSynced: false
  systemStats: {}
  finalizers: {}
