# syncRevision: 30565a3ae746543a
metadata:
  name: git-sync-test-1772762415
  labels:
    homelab.io/test: git-sync
  annotations: {}
  finalizers: []
  creationTimestamp: '2026-03-06T02:00:17.364566Z'
spec:
  hostname: git-sync-test-1772762415.homelab.local
  os:
    distro: ubuntu-24.04-live
    arch: x86_64
  macAddress: 02:00:00:00:00:b4
  hardware:
    cpu: 2
    ramGiB: 4
  storage:
    disk_name: sda
    partitions:
    - partition_type: primary
      alloc_type: percentage
      size: 100
      fs_type: ext4
      flags:
      - lvm
  networking:
    interfaces:
    - name: eth0
      dhcp: true
    vlans: []
  users:
  - name: admin
    groups:
    - wheel
  groups:
  - test_nodes
  featureFlags:
    provisioned:
      enabled: false
    k8s:
      enabled: false
      role: worker
    monitoring:
      enabled: true
    backup:
      enabled: false
    daemon:
      enabled: true
  pauseReconciliation: false
  tags:
    homelab.io/test: git-sync
status:
  conditions:
  - type: InventorySynced
    status: 'False'
    reason: SyncFailed
    message: 'Command failed (git clone --branch main file:///var/folders/cj/yr4jplmd6bzcr6qdjyjm944c0000gn/T/tmp.noZkeXvUXH/inventory-remote.git
      /var/folders/cj/yr4jplmd6bzcr6qdjyjm944c0000gn/T/tmp.noZkeXvUXH/inventory-local): '
    lastTransitionTime: '2026-03-06T02:28:16.907832Z'
  - type: HostvarsSynced
    status: 'False'
    reason: SyncFailed
    message: 'Command failed (git clone --branch main file:///var/folders/cj/yr4jplmd6bzcr6qdjyjm944c0000gn/T/tmp.noZkeXvUXH/hostvars-remote.git
      /var/folders/cj/yr4jplmd6bzcr6qdjyjm944c0000gn/T/tmp.noZkeXvUXH/hostvars-local): '
    lastTransitionTime: '2026-03-06T02:28:16.907849Z'
  - type: PipelineReady
    status: 'False'
    reason: SyncFailed
    message: Waiting for sync
    lastTransitionTime: '2026-03-06T02:28:16.907855Z'
  - type: Reachable
    status: 'False'
    lastTransitionTime: '2026-03-06T02:00:33.358353Z'
  - type: DaemonReady
    status: 'False'
    lastTransitionTime: '2026-03-06T02:00:33.358508Z'
  features:
    provisioned:
      installed: false
    k8s:
      installed: false
    monitoring:
      installed: false
    backup:
      installed: false
    daemon:
      installed: false
  inventorySynced: false
  hostvarsSynced: false
  systemStats: {}
  finalizers: {}
